
images:
  - name: quay.io/operator-framework/olm
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:036e84019c195ec4fa3bb7709ef3ff267dec7e5061cdb701cfa6809ccc6b34c3
  - name: quay.io/operator-framework/configmap-operator-registry
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:9a685cb45b8f38321105195418e551887db79198f8ee7581aae020ee8c7787be
  - name: quay.io/openshift/origin-kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:290478ee07daaf4795f9925609bcd24e4ddcec635a28d5f9f70da8592c4458c6

patches:
  - patch: |-
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OPERATOR_REGISTRY_IMAGE 
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9a685cb45b8f38321105195418e551887db79198f8ee7581aae020ee8c7787be
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OLM_IMAGE 
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:036e84019c195ec4fa3bb7709ef3ff267dec7e5061cdb701cfa6809ccc6b34c3
    target:
      kind: Deployment
      labelSelector: app=catalog-operator
