
images:
  - name: quay.io/operator-framework/olm
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:354d018cc6c898a670857ac6623d350ff806feeb0ed7b9ac943dd38d3a0eea94
  - name: quay.io/operator-framework/configmap-operator-registry
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:f5a0f34d63a9a15c2241e78001cf596e0d813f3afac08230ffebba05ea970ae6
  - name: quay.io/openshift/origin-kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:47497f5076175d0e2d7c7090abcb379ea2a48e6faa8271cc91acf260cfb1f6e8

patches:
  - patch: |-
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OPERATOR_REGISTRY_IMAGE
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f5a0f34d63a9a15c2241e78001cf596e0d813f3afac08230ffebba05ea970ae6
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OLM_IMAGE
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:354d018cc6c898a670857ac6623d350ff806feeb0ed7b9ac943dd38d3a0eea94
    target:
      kind: Deployment
      labelSelector: app=catalog-operator
