
images:
  - name: quay.io/operator-framework/olm
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:b6f0760e1573d391005d835cc657512368f93240b54bf7b65f68a6f64289f2f7
  - name: quay.io/operator-framework/configmap-operator-registry
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:cc40ec395d9bc0ed579ddd670e09024314ab5e7bfcf9335199c84ec5622ac47e
  - name: quay.io/openshift/origin-kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:a6966ecebd2bceadcb15a49867289ee899325db83f052ef817f7a8a68d0ae12f

patches:
  - patch: |-
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OPERATOR_REGISTRY_IMAGE 
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:cc40ec395d9bc0ed579ddd670e09024314ab5e7bfcf9335199c84ec5622ac47e
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OLM_IMAGE 
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b6f0760e1573d391005d835cc657512368f93240b54bf7b65f68a6f64289f2f7
    target:
      kind: Deployment
      labelSelector: app=catalog-operator
