
images:
  - name: quay.io/operator-framework/olm
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:5934bd8723241db6c6f433fbedc7134b02bd0f010e0c10cd06448caec30ab35e
  - name: quay.io/operator-framework/configmap-operator-registry
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:cc693e2efd53e074d662d37cb024c7f7d1b7d2ca231a9fcbfc052724787bfa1e
  - name: quay.io/openshift/origin-kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:268ef89dd78b673cf808e13f4f266423ba6e06c6cba8184a7be7f526b009f5f2

patches:
  - patch: |-
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OPERATOR_REGISTRY_IMAGE 
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:cc693e2efd53e074d662d37cb024c7f7d1b7d2ca231a9fcbfc052724787bfa1e
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OLM_IMAGE 
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:5934bd8723241db6c6f433fbedc7134b02bd0f010e0c10cd06448caec30ab35e
    target:
      kind: Deployment
      labelSelector: app=catalog-operator
