
images:
  - name: quay.io/operator-framework/olm
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:55bd31be5bed96032d9a19fba4c5230c162717f9d68fc418be4d8796f2dfccb3
  - name: quay.io/operator-framework/configmap-operator-registry
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:df5929656b064e258ac3014379173fc37939b3cbc97f3bbe0c9804514ad87d98
  - name: quay.io/openshift/origin-kube-rbac-proxy
    newName: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    digest: sha256:21b1ec1ffeb289a947603674cda13a84c35545b04e4940dfef055147908220ab

patches:
  - patch: |-
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OPERATOR_REGISTRY_IMAGE 
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:df5929656b064e258ac3014379173fc37939b3cbc97f3bbe0c9804514ad87d98
     - op: add
       path: /spec/template/spec/containers/0/env/-
       value:
         name: OLM_IMAGE 
         value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:55bd31be5bed96032d9a19fba4c5230c162717f9d68fc418be4d8796f2dfccb3
    target:
      kind: Deployment
      labelSelector: app=catalog-operator
