apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: caikit-tgis-runtime
  annotations:
    openshift.io/display-name: Caikit TGIS ServingRuntime for KServe
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/port: '3000'
    prometheus.io/path: /metrics
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: caikit
  containers:
    - name: kserve-container
      image: tgis-image
      command:
        - text-generation-launcher
      args:
        - --model-name=/mnt/models/artifacts/
      env:
        - name: HF_HOME
          value: /tmp/hf_home
    - name: transformer-container
      image: caikit-tgis-image
      env:
        - name: RUNTIME_LOCAL_MODELS_DIR
          value: /mnt/models
        - name: HF_HOME
          value: /tmp/hf_home
        - name: RUNTIME_GRPC_ENABLED
          value: 'false'
        - name: RUNTIME_HTTP_ENABLED
          value: 'true'
      ports:
        - containerPort: 8080
          protocol: TCP
