---
# setup-microshift-host tasks

- name: install firewalld & packages
  ansible.builtin.dnf:
    name: "{{ install_packages }}"
    state: present
    update_cache: true

- name: determine system architecture
  ansible.builtin.set_fact:
    go_arch: amd64
  when: ansible_facts['architecture'] == "x86_64"

- name: create target directory for go version
  ansible.builtin.file:
    path: "{{ go_install_dir }}"
    state: directory

- name: download & extract newer version of golang
  ansible.builtin.unarchive:
    src: https://go.dev/dl/go{{ go_version }}.linux-{{ go_arch }}.tar.gz
    dest: "{{ go_install_dir }}"
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

- name: create symbolic links
  ansible.builtin.file:
    src: "{{ go_install_dir }}/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  with_items: "{{ go_files }}"

- name: check firewalld service status
  ansible.builtin.systemd:
    name: firewalld
  register: firewalld_status
  ignore_errors: true

- name: start and enable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes
  when: firewalld_status.status.UnitFileState is not defined or firewalld_status.status.UnitFileState != 'masked'

- name: check if rhel vg exists
  ansible.builtin.command: vgdisplay -s {{ vg_name }}
  register: rhel_vg_present
  ignore_errors: true

- name: check if lvm disk exists
  ansible.builtin.stat:
    path: "{{ lvm_disk }}"
  register: lvm_disk_stat
  when: rhel_vg_present.rc != 0

- name: create a volume group on top of secondary disk for topolvm
  community.general.lvg:
    vg: "{{ vg_name }}"
    pvs: "{{ lvm_disk }}"
  when:
    - rhel_vg_present.rc != 0
    - lvm_disk_stat.stat.exists

- name: notify about missing lvm disk
  ansible.builtin.debug:
    msg: "LVM disk {{ lvm_disk }} not found, skipping TopoLVM volume group creation"
  when:
    - rhel_vg_present.rc != 0
    - lvm_disk_stat is defined
    - not lvm_disk_stat.stat.exists

- name: Configure TopoLVM storage
  include_tasks: storage.yml
  when: rhel_vg_present.rc == 0 or (lvm_disk_stat is defined and lvm_disk_stat.stat.exists)

- name: upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    nobest: true
  notify: reboot machine

- name: flush handlers
  ansible.builtin.meta: flush_handlers
