apiVersion: v1
kind: Pod
metadata:
  name: cert-manager-images
  namespace: system
spec:
  containers:
  - name: cert-manager-webhook
    image: cert-manager-webhook:latest
  - name: cert-manager-ca-injector
    image: cert-manager-ca-injector:latest
  - name: cert-manager-controller
    image: cert-manager-controller:latest
  - name: cert-manager-acmesolver
    image: cert-manager-acmesolver:latest
  - name: cert-manager-istiocsr
    image: cert-manager-istiocsr:latest
  restartPolicy: Never 