apiVersion: v1
kind: Service
metadata:
  namespace: postgresql
  name: postgresql
  labels:
    app: postgreSQL
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgreSQL