---
# Shared microshift version-specific configuration
# This file is included by multiple roles

# Version-specific pod counts
# expected_pods is the number of non-storage pods that should be running first
# all_pods is the total number of pods that should be running after the boot script has completed
microshift_versions:
  "4.16":
    expected_pods: 6
    all_pods: 10
  "4.17":
    expected_pods: 6
    all_pods: 10
  "4.18":
    expected_pods: 6
    all_pods: 9 
  "4.19":
    expected_pods: 6
    all_pods: 9 
