apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: postgresql
  name: postgres-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: topolvm-provisioner