apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: postgresql 
  name: postgresql
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgreSQL    
  template:
    metadata:
      namespace: postgresql 
      labels:
        app: postgreSQL
    spec:
      containers:
        - image: postgres:9.6.2-alpine
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: gitlab
            - name: POSTGRES_DB
              value: gitlabhq_production
            - name: POSTGRES_PASSWORD
              value: gitlab
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgres-claim