apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd/full/serving.kserve.io_clusterservingruntimes.yaml
- namespace.yaml
- overlays/odh/

patches:
- path: inferenceservice-config-microshift-patch.yaml
